# Generated by Django 3.2.3 on 2021-05-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_some_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.RemoveField(
            model_name='runsetresult',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='log_level',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='instructionresult',
            name='status',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='runexecutioninfo',
            name='run_status_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='runsetresult',
            name='status',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='testcaseexecutioninfo',
            name='latest_run_trigger_source',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LogLevel',
        ),
        migrations.DeleteModel(
            name='SourceType',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
