# Generated by Django 3.2.3 on 2021-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_use_choices_for_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='color',
            field=models.CharField(choices=[('BLU', 'Blue'), ('GRE', 'Green'), ('ORA', 'Orange'), (
                'RED', 'Red'), ('GRY', 'Grey'), ('WHT', 'White')], default='WHT', max_length=3),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='color',
            field=models.CharField(choices=[('BLU', 'Blue'), ('GRE', 'Green'), ('ORA', 'Orange'), (
                'RED', 'Red'), ('GRY', 'Grey'), ('WHT', 'White')], default='WHT', max_length=3),
        ),
    ]
