# Generated by Django 3.2.3 on 2021-05-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverProperty',
        ),
        migrations.AlterUniqueTogether(
            name='drivervendor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='drivervendor',
            name='driver_type',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='driver_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructiontype',
            name='driver_type',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DriverType',
        ),
        migrations.DeleteModel(
            name='DriverVendor',
        ),
    ]
