# Generated by Django 3.2.3 on 2021-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='runexecutioninfo',
            name='run_group_id',
        ),
        migrations.RemoveField(
            model_name='runset',
            name='group',
        ),
        migrations.RemoveField(
            model_name='runsetresult',
            name='group',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='group',
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.TextField(default='log'),
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('id', 'uuid'), ('id', 'is_finished'), ('id', 'run_set_result'), ('id', 'test_case_0'), ('id', 'priority'), ('id', 'start_at', 'end_at')},
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.RemoveField(
            model_name='run',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
