# Generated by Django 3.2.3 on 2021-05-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='driverpack',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='instructionoverwrite',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='runset',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='runset',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='systemrequirementpack',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='testcaseoverwrite',
            name='copy_from_id',
        ),
        migrations.RemoveField(
            model_name='testcasesharefolder',
            name='copy_from_id',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='parameter',
            field=models.JSONField(default=dict),
        ),
    ]
