# Generated by Django 3.2.3 on 2021-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_some_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
