# Generated by Django 3.2.3 on 2021-05-17 04:58

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_alias_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vendor_name',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='ref_test_case_overwrite_name',
        ),
        migrations.RemoveField(
            model_name='instructionresult',
            name='instruction_0',
        ),
        migrations.RemoveField(
            model_name='run',
            name='system_requirement_pack_0',
        ),
        migrations.RemoveField(
            model_name='run',
            name='system_requirement_pack'
        ),
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='elementtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailnotificationtarget',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='instructionaction',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='instructionoption',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='instructionresult',
            name='instruction_options',
        ),
        migrations.AddField(
            model_name='instructionresult',
            name='instruction_options',
            field=models.ManyToManyField(to='api.InstructionOption'),
        ),
        migrations.AlterField(
            model_name='instructiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projectexecutioninfo',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projectreportinfo',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='run',
            name='system_requirement_pack',
            field=models.JSONField(
                blank=True, db_column='system_requirement_pack', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='systemrequirementpack',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testcaseexecutioninfo',
            name='test_case_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testcaseoption',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testcaseoverwrite',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testcasesharefolder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
