# Generated by Django 3.2.3 on 2021-05-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_chaneg_name_to_char_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='elementlocator',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='elementtype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructionaction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructionoption',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instructiontype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testcaseoption',
            name='is_active',
        ),
    ]
