# Generated by Django 3.2.3 on 2021-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='driverpack',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='element',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='projectexecutioninfo',
            name='project_is_deleted',
        ),
        migrations.RemoveField(
            model_name='runset',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='systemrequirementpack',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testcaseexecutioninfo',
            name='test_case_is_deleted',
        ),
        migrations.RemoveField(
            model_name='testcaseoverwrite',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='testcasesharefolder',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='alias',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverpack',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexecutioninfo',
            name='project_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemrequirementpack',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcaseexecutioninfo',
            name='test_case_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcaseoverwrite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcasesharefolder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
