# Generated by Django 3.2.3 on 2021-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_more_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionbundleentry',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='instructionbundleentry',
            name='instruction_action',
        ),
        migrations.RemoveField(
            model_name='instructionbundleentry',
            name='instruction_bundle',
        ),
        migrations.RemoveField(
            model_name='instructionoptionentry',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='instructionoptionentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testcaseoptionentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testcaseoptionentry',
            name='test_case',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='steplog',
            name='step_log_type',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_type',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='InstructionBundle',
        ),
        migrations.DeleteModel(
            name='InstructionBundleEntry',
        ),
        migrations.DeleteModel(
            name='InstructionOptionEntry',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
        migrations.DeleteModel(
            name='StepLogType',
        ),
        migrations.DeleteModel(
            name='TestCaseOptionEntry',
        ),
    ]
