# Generated by Django 3.2.3 on 2021-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_more_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterScript',
        ),
        migrations.DeleteModel(
            name='TestCaseType',
        ),
        migrations.RemoveField(
            model_name='runexecutioninfo',
            name='run_status_id',
        ),
        migrations.RemoveField(
            model_name='runexecutioninfo',
            name='run_type_id',
        ),
        migrations.RemoveField(
            model_name='runsetresult',
            name='priority',
        ),
        migrations.AddField(
            model_name='runexecutioninfo',
            name='run_type',
            field=models.CharField(choices=[('PRD', 'Production'), ('DEV', 'Development')], default='PRD', max_length=3),
        ),
        migrations.AddField(
            model_name='runexecutioninfo',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WIP', 'Wip'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('STOP', 'Stop'), ('N/A', 'Na'), ('T/O', 'Timeout'), ('TERM', 'Terminated')], default='NEW', max_length=5),
        ),
        migrations.AlterField(
            model_name='driverpackdriveraliasmap',
            name='driver_aliases',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='driverpackdrivertypemap',
            name='driver_types',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='log_level',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARN', 'Warn'), ('INFO', 'Info'), ('DEBUG', 'Debug'), ('TRACE', 'Trace')], default='INFO', max_length=5),
        ),
        migrations.AlterField(
            model_name='instructionoptionmap',
            name='element_type_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='instructionoptionmap',
            name='instruction_action_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='instructionresult',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WIP', 'Wip'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('STOP', 'Stop'), ('N/A', 'Na'), ('T/O', 'Timeout'), ('TERM', 'Terminated')], default='NEW', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PERS', 'Personal'), ('GROUP', 'Group')], default='GROUP', max_length=5),
        ),
        migrations.AlterField(
            model_name='projectexecutioninfo',
            name='active_test_case_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='projectexecutioninfo',
            name='executed_test_case_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='projectexecutioninfo',
            name='passed_test_case_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='projectexecutioninfo',
            name='test_case_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WIP', 'Wip'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('STOP', 'Stop'), ('N/A', 'Na'), ('T/O', 'Timeout'), ('TERM', 'Terminated')], default='NEW', max_length=5),
        ),
        migrations.AlterField(
            model_name='runset',
            name='run_set_type',
            field=models.CharField(choices=[('INT', 'Internal'), ('EXT', 'External')], default='INT', max_length=3),
        ),
        migrations.AlterField(
            model_name='runsetaliasnamemap',
            name='alias_names',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='runsetresult',
            name='failed_run_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='runsetresult',
            name='passed_run_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='runsetresult',
            name='run_ids',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='runsetresult',
            name='run_set_type',
            field=models.BigIntegerField(choices=[('INT', 'Internal'), ('EXT', 'External')], default='INT'),
        ),
        migrations.AlterField(
            model_name='runsetresult',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WIP', 'Wip'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('STOP', 'Stop'), ('N/A', 'Na'), ('T/O', 'Timeout'), ('TERM', 'Terminated')], default='NEW', max_length=5),
        ),
        migrations.AlterField(
            model_name='steplog',
            name='step_log_type',
            field=models.CharField(choices=[('INS', 'Instruction'), ('INS_BIN', 'Instruction Begin'), ('INS_END', 'Instruction End'), ('PASS', 'Pass'), ('ELE_NF', 'Element Not Found'), ('T/O', 'Time Out'), ('EXCEPT', 'Exception'), ('FAIL', 'Fail')], default='INS', max_length=7),
        ),
        migrations.AlterField(
            model_name='systemrequirement',
            name='system_requirement_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('RAM', 'Ram'), ('OS', 'Os'), ('B/W', 'Bandwidth')], default='CORE', max_length=4),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_type',
            field=models.CharField(choices=[('JSON', 'Json'), ('JM', 'Jmeter'), ('ANDRO', 'Android')], default='JSON', max_length=5),
        ),
        migrations.AlterField(
            model_name='testcasedriveraliasmap',
            name='driver_aliases',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcasedrivertypemap',
            name='driver_types',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcaseexecutioninfo',
            name='latest_run_status_id',
            field=models.CharField(choices=[('NEW', 'New'), ('WIP', 'Wip'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('STOP', 'Stop'), ('N/A', 'Na'), ('T/O', 'Timeout'), ('TERM', 'Terminated')], default='NEW', max_length=5),
        ),
        migrations.AlterField(
            model_name='testcaseinstructiontypemap',
            name='instruction_types',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='RunSetType',
        ),
        migrations.DeleteModel(
            name='SystemRequirementType',
        ),
    ]
