# Generated by Django 3.2.3 on 2021-05-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm_api', '0004_remove _more_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='executionlog',
            table='execution_log',
        ),
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
        migrations.AlterModelTable(
            name='instructionresult',
            table='instruction_result',
        ),
        migrations.AlterModelTable(
            name='steplog',
            table='step_log',
        ),
    ]
